sudo: false # faster builds
language: java
jdk:
 - oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer

script:
  - mvn clean verify
  - mvn "cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
